import type { Offer } from './types';

export const MOCK_FUTURE_OFFERS: Offer[] = [
  // 2026-06-01 changes
  { id: 'f1',  type: 'future', offerKind: 'Performance', date: '2026-06-01', country: 'UAE',    tariff: 'Basic',   platform: 'iOS',     offerName: 'Summer Basic iOS UAE',    offerValue: '3 months for price of 1', price: '29.99 AED', duration: '3 months',  promoCode: 'SUMMER26', source: 'Google Sheet', dateFrom: '2026-06-01', description: 'Summer promotional offer for UAE iOS subscribers — 3 months subscription at the price of 1. Part of the post-Ramadan retention campaign targeting lapsed and at-risk users.', comment: 'Ramadan follow-up campaign', status: 'Planned', lastUpdated: '2026-05-10', buttonTextEn: 'Get 3 months for AED 29.99', buttonTextAr: 'احصل على 3 أشهر مقابل 29.99 درهم', disclaimerEn: 'Then AED 29.99 per month. Cancel anytime.', disclaimerAr: 'ثم 29.99 درهماً شهرياً. يمكن الإلغاء في أي وقت.' },
  { id: 'f2',  type: 'future', offerKind: 'Performance', date: '2026-06-01', country: 'UAE',    tariff: 'Basic',   platform: 'Android', offerName: 'Summer Basic Android UAE', offerValue: '3 months for price of 1', price: '29.99 AED', duration: '3 months',  promoCode: 'SUMMER26', source: 'Google Sheet', dateFrom: '2026-06-01', comment: 'Ramadan follow-up campaign', status: 'Planned', lastUpdated: '2026-05-10' },
  { id: 'f3',  type: 'future', offerKind: 'Performance', date: '2026-06-01', country: 'KSA',    tariff: 'Basic',   platform: 'iOS',     offerName: 'Summer Basic iOS KSA',    offerValue: '2 months free',           price: '39.99 SAR', duration: '2 months',  promoCode: 'KSA26',    source: 'Google Sheet', dateFrom: '2026-06-01', comment: 'KSA national day prep',      status: 'Planned', lastUpdated: '2026-05-12' },
  { id: 'f4',  type: 'future', offerKind: 'Performance', date: '2026-06-01', country: 'Egypt',  tariff: 'Premium', platform: 'Android', offerName: 'Egypt Premium Launch',    offerValue: '50% off first month',     price: '99 EGP',    duration: '1 month',   promoCode: 'EGYPT50',  source: 'Google Sheet', dateFrom: '2026-06-01', comment: 'New Premium tier launch EG', status: 'Planned', lastUpdated: '2026-05-14' },
  // 2026-06-15 changes
  { id: 'f5',  type: 'future', offerKind: 'Main product', date: '2026-06-15', country: 'Kuwait', tariff: 'Basic',   platform: 'Native',  offerName: 'Q3 Basic Native KW',      offerValue: '1 month free',            price: '2.49 KWD',  duration: '1 month',   promoCode: '',         source: 'Google Sheet', dateFrom: '2026-06-15', comment: '',                           status: 'Planned', lastUpdated: '2026-05-15' },
  { id: 'f6',  type: 'future', offerKind: 'Test product',        date: '2026-06-15', country: 'Qatar',  tariff: 'Premium', platform: 'iOS',     offerName: 'Qatar Premium iOS Q3',    offerValue: 'Free trial 14 days',      price: '49.99 QAR', duration: '14 days',   promoCode: 'QAT14',    source: 'Google Sheet', dateFrom: '2026-06-15', comment: 'A/B test with 7-day trial',  status: 'Planned', lastUpdated: '2026-05-15' },
  { id: 'f7',  type: 'future', offerKind: 'Performance', date: '2026-06-15', country: 'Oman',   tariff: 'Basic',   platform: 'iOS',     offerName: 'Oman Basic iOS Summer',   offerValue: '25% off',                 price: '1.99 OMR',  duration: '2 months',  promoCode: 'OMAN25',   source: 'Google Sheet', dateFrom: '2026-06-15', comment: '',                           status: 'Draft',   lastUpdated: '2026-05-16' },
  { id: 'f8',  type: 'future', offerKind: 'Performance',        date: '2026-06-15', country: 'Bahrain',tariff: 'Crunchyroll', platform: 'Android', offerName: 'Crunchyroll BH Summer', offerValue: '7 days free + 20% off', price: '3.99 BHD',  duration: '3 months',  promoCode: 'CR7BH',    source: 'Google Sheet', dateFrom: '2026-06-15', comment: 'Anime season launch',        status: 'Planned', lastUpdated: '2026-05-16' },
];

export const MOCK_CURRENT_OFFERS: Offer[] = [
  // UAE
  { id: 'c1',  type: 'current', offerKind: 'Main product', country: 'UAE',    tariff: 'Basic',       platform: 'iOS',     offerName: 'Standard Monthly',      price: '34.99 AED', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c2',  type: 'current', offerKind: 'Main product', country: 'UAE',    tariff: 'Basic',       platform: 'Android', offerName: 'Standard Monthly',      price: '34.99 AED', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c3',  type: 'current', offerKind: 'Main product', country: 'UAE',    tariff: 'Basic',       platform: 'Native',  offerName: 'Standard Monthly',      price: '29.99 AED', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c4',  type: 'current', offerKind: 'Main product', country: 'UAE',    tariff: 'Premium',     platform: 'iOS',     offerName: 'Premium Monthly',       price: '59.99 AED', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c5',  type: 'current', offerKind: 'Main product', country: 'UAE',    tariff: 'Premium',     platform: 'Android', offerName: 'Premium Monthly',       price: '59.99 AED', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c6',  type: 'current', offerKind: 'Main product', country: 'UAE',    tariff: 'Crunchyroll', platform: 'iOS',     offerName: 'Crunchyroll Bundle',    price: '49.99 AED', duration: '1 month',  source: 'DataLens', dateFrom: '2026-03-01', status: 'Active', lastUpdated: '2026-03-01' },
  // KSA
  { id: 'c7',  type: 'current', offerKind: 'Main product', country: 'KSA',    tariff: 'Basic',       platform: 'iOS',     offerName: 'Standard Monthly',      price: '44.99 SAR', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c8',  type: 'current', offerKind: 'Main product', country: 'KSA',    tariff: 'Basic',       platform: 'Android', offerName: 'Standard Monthly',      price: '44.99 SAR', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c9',  type: 'current', offerKind: 'Main product', country: 'KSA',    tariff: 'Premium',     platform: 'iOS',     offerName: 'Premium Monthly',       price: '79.99 SAR', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  // Egypt
  { id: 'c10', type: 'current', offerKind: 'Main product', country: 'Egypt',  tariff: 'Basic',       platform: 'iOS',     offerName: 'Standard Monthly',      price: '149 EGP',   duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c11', type: 'current', offerKind: 'Main product', country: 'Egypt',  tariff: 'Basic',       platform: 'Android', offerName: 'Standard Monthly',      price: '149 EGP',   duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c12', type: 'current', offerKind: 'Main product', country: 'Egypt',  tariff: 'Basic',       platform: 'Native',  offerName: 'Standard Monthly',      price: '129 EGP',   duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  // Kuwait
  { id: 'c13', type: 'current', offerKind: 'Main product', country: 'Kuwait', tariff: 'Basic',       platform: 'iOS',     offerName: 'Standard Monthly',      price: '2.99 KWD',  duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c14', type: 'current', offerKind: 'Main product', country: 'Kuwait', tariff: 'Premium',     platform: 'iOS',     offerName: 'Premium Monthly',       price: '4.99 KWD',  duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  // Qatar
  { id: 'c15', type: 'current', offerKind: 'Main product', country: 'Qatar',  tariff: 'Basic',       platform: 'iOS',     offerName: 'Standard Monthly',      price: '39.99 QAR', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c16', type: 'current', offerKind: 'Main product', country: 'Qatar',  tariff: 'Basic',       platform: 'Android', offerName: 'Standard Monthly',      price: '39.99 QAR', duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  // Oman
  { id: 'c17', type: 'current', offerKind: 'Main product', country: 'Oman',   tariff: 'Basic',       platform: 'iOS',     offerName: 'Standard Monthly',      price: '2.49 OMR',  duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c18', type: 'current', offerKind: 'Main product', country: 'Oman',   tariff: 'Basic',       platform: 'Android', offerName: 'Standard Monthly',      price: '2.49 OMR',  duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  // Bahrain
  { id: 'c19', type: 'current', offerKind: 'Main product', country: 'Bahrain',tariff: 'Basic',       platform: 'iOS',     offerName: 'Standard Monthly',      price: '3.99 BHD',  duration: '1 month',  source: 'DataLens', dateFrom: '2026-04-01', status: 'Active', lastUpdated: '2026-04-01' },
  { id: 'c20', type: 'current', offerKind: 'Main product', country: 'Bahrain',tariff: 'Crunchyroll', platform: 'iOS',     offerName: 'Crunchyroll Bundle',    price: '5.99 BHD',  duration: '1 month',  source: 'DataLens', dateFrom: '2026-03-01', status: 'Active', lastUpdated: '2026-03-01' },
];

export const MOCK_OLD_OFFERS: Offer[] = [
  { id: 'o1',  type: 'old', offerKind: 'Performance',       country: 'UAE',    tariff: 'Basic',   platform: 'iOS',     offerName: 'Ramadan Basic iOS UAE',   offerValue: 'First month free', price: '0 AED',     duration: '1 month', promoCode: 'RAMADAN26', source: 'DataLens', dateFrom: '2026-03-01', dateTo: '2026-04-10', status: 'Expired', lastUpdated: '2026-04-10' },
  { id: 'o2',  type: 'old', offerKind: 'Performance',       country: 'UAE',    tariff: 'Basic',   platform: 'Android', offerName: 'Ramadan Basic Android',   offerValue: 'First month free', price: '0 AED',     duration: '1 month', promoCode: 'RAMADAN26', source: 'DataLens', dateFrom: '2026-03-01', dateTo: '2026-04-10', status: 'Expired', lastUpdated: '2026-04-10' },
  { id: 'o3',  type: 'old', offerKind: 'Performance', country: 'UAE',    tariff: 'Premium', platform: 'iOS',     offerName: 'Ramadan Premium iOS',     offerValue: '30% off',          price: '41.99 AED', duration: '1 month', promoCode: 'RPREM30',   source: 'DataLens', dateFrom: '2026-03-01', dateTo: '2026-04-10', status: 'Expired', lastUpdated: '2026-04-10' },
  { id: 'o4',  type: 'old', offerKind: 'Test product',       country: 'KSA',    tariff: 'Basic',   platform: 'iOS',     offerName: 'Ramadan Basic iOS KSA',   offerValue: '2 weeks free',     price: '22.49 SAR', duration: '2 weeks', promoCode: 'RKSA14',    source: 'DataLens', dateFrom: '2026-03-01', dateTo: '2026-04-10', status: 'Expired', lastUpdated: '2026-04-10' },
  { id: 'o5',  type: 'old', offerKind: 'Performance', country: 'Egypt',  tariff: 'Basic',   platform: 'iOS',     offerName: 'Egypt New Year Basic',    offerValue: '40% off',          price: '89 EGP',    duration: '1 month', promoCode: 'EGY40',     source: 'DataLens', dateFrom: '2026-01-01', dateTo: '2026-01-31', status: 'Expired', lastUpdated: '2026-01-31' },
  { id: 'o6',  type: 'old', offerKind: 'Test product',       country: 'Kuwait', tariff: 'Premium', platform: 'Android', offerName: 'Kuwait Spring Premium',   offerValue: 'Free 7 days',      price: '0 KWD',     duration: '7 days',  promoCode: '',          source: 'DataLens', dateFrom: '2026-02-15', dateTo: '2026-03-15', status: 'Expired', lastUpdated: '2026-03-15' },
  { id: 'o7',  type: 'old', offerKind: 'Performance', country: 'Qatar',  tariff: 'Basic',   platform: 'Native',  offerName: 'Qatar Basic Native Feb',  offerValue: '10% off',          price: '35.99 QAR', duration: '1 month', promoCode: 'QFB10',     source: 'DataLens', dateFrom: '2026-02-01', dateTo: '2026-02-28', status: 'Expired', lastUpdated: '2026-02-28' },
  { id: 'o8',  type: 'old', offerKind: 'Performance', country: 'Oman',   tariff: 'Basic',   platform: 'iOS',     offerName: 'Oman Winter Basic',       offerValue: '15% off',          price: '2.12 OMR',  duration: '1 month', promoCode: 'OMAN15',    source: 'DataLens', dateFrom: '2026-01-15', dateTo: '2026-02-28', status: 'Expired', lastUpdated: '2026-02-28' },
  { id: 'o9',  type: 'old', offerKind: 'Test product',       country: 'Bahrain',tariff: 'Basic',   platform: 'Android', offerName: 'Bahrain Launch Offer',    offerValue: 'First month free', price: '0 BHD',     duration: '1 month', promoCode: 'BHLAUNCH',  source: 'DataLens', dateFrom: '2026-03-10', dateTo: '2026-04-10', status: 'Expired', lastUpdated: '2026-04-10' },
  { id: 'o10', type: 'old', offerKind: 'Test product',       country: 'UAE',    tariff: 'Crunchyroll', platform: 'iOS', offerName: 'Crunchyroll Intro UAE',   offerValue: 'First month free', price: '0 AED',     duration: '1 month', promoCode: 'CRINTRO',   source: 'DataLens', dateFrom: '2026-02-01', dateTo: '2026-03-01', status: 'Expired', lastUpdated: '2026-03-01' },
  { id: 'o11', type: 'old', offerKind: 'Performance', country: 'KSA',    tariff: 'Premium', platform: 'iOS',     offerName: 'KSA Premium Spring',      offerValue: '20% off',          price: '63.99 SAR', duration: '1 month', promoCode: 'KSAP20',    source: 'DataLens', dateFrom: '2026-03-20', dateTo: '2026-04-20', status: 'Expired', lastUpdated: '2026-04-20' },
  { id: 'o12', type: 'old', offerKind: 'Test product',       country: 'Egypt',  tariff: 'Premium', platform: 'Android', offerName: 'Egypt Premium Trial',     offerValue: '7 days free',      price: '0 EGP',     duration: '7 days',  promoCode: 'EGYP7',     source: 'DataLens', dateFrom: '2026-04-01', dateTo: '2026-04-30', status: 'Expired', lastUpdated: '2026-04-30' },
];
